### ISSUE TITLE
Sort city and agas by name

### ISSUE THREAD

**Issue by eli-zada** [eli-zada/CovidMunView-FE#4]
Filter unknown agas from the FE

**Comment by moraneden** [comment]
Done
https://github.com/eli-zada/CovidMunView-FE/commit/eec708dcada96f9e338c0c44a99ab1d358231642
https://github.com/eli-zada/CovidMunView-FE/commit/7a646aeeaea8d6636c87adec4cf9ee959d30e78a

**Comment by moraneden** [comment]
Done with 2 commits
